# Generated by Django 5.1.4 on 2025-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=50),
        ),
    ]
