# Generated by Django 5.1.4 on 2025-01-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0002_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='fields',
        ),
        migrations.AlterField(
            model_name='document',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg_ctaima_app.resource'),
        ),
        migrations.CreateModel(
            name='FieldToExtract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_types', models.ManyToManyField(related_name='fields_to_extract', to='tfg_ctaima_app.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FieldToValidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('treshold', models.FloatField(blank=True, default=80, null=True)),
                ('document_types', models.ManyToManyField(related_name='fields_to_validate', to='tfg_ctaima_app.documenttype')),
            ],
        ),
    ]
