# Generated by Django 5.1.4 on 2024-12-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
