# Generated by Django 5.1.4 on 2025-01-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0003_remove_documenttype_fields_alter_document_resource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='number_id',
            new_name='worker_id',
        ),
    ]
