# Generated by Django 5.1.4 on 2025-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0004_rename_tax_id_company_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtovalidate',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
