# Generated by Django 5.1.4 on 2025-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0005_fieldtovalidate_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtovalidate',
            old_name='value',
            new_name='expected_value',
        ),
        migrations.AddField(
            model_name='fieldtovalidate',
            name='obtained_value',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
