# Generated by Django 5.1.4 on 2025-01-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0006_rename_value_fieldtovalidate_expected_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtovalidate',
            name='obtained_value',
        ),
    ]
