# Generated by Django 5.1.4 on 2025-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0008_document_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
