# Generated by Django 5.1.4 on 2025-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0012_document_company_alter_document_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name', 'company_id'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['id', 'timestamp'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
