# Generated by Django 5.1.4 on 2025-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0014_remove_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='api_doc_type_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
