# Generated by Django 5.1.4 on 2025-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0015_document_api_doc_type_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='api_doc_type_text',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='api_doc_type_text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
