# Generated by Django 5.1.4 on 2025-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0016_remove_document_api_doc_type_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='pattern_invalidation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='pattern_validation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
