# Generated by Django 5.1.4 on 2025-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0018_alter_fieldtovalidate_expected_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtovalidate',
            name='expected_value',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
