# Generated by Django 5.1.4 on 2025-02-19 09:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0019_alter_fieldtovalidate_expected_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='associated_entity',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='associated_entities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('resource', 'Resource'), ('company', 'Company')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
