# Generated by Django 5.1.4 on 2025-02-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0021_alter_company_email_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='company',
        ),
    ]
