# Generated by Django 5.1.4 on 2025-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0023_alter_company_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='sign',
            field=models.BooleanField(default=False),
        ),
    ]
