# Generated by Django 5.1.4 on 2025-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0024_documenttype_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
