# Generated by Django 5.1.4 on 2025-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0009_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
