# Generated by Django 5.1.4 on 2025-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0010_alter_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='associated_entity',
            field=models.CharField(choices=[('resource', 'Resource'), ('company', 'Company')], default='resource', max_length=50),
        ),
    ]
