# Generated by Django 5.1.4 on 2025-02-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0011_documenttype_associated_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfg_ctaima_app.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfg_ctaima_app.resource'),
        ),
    ]
