# Generated by Django 5.1.4 on 2025-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0013_alter_company_options_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
