# Generated by Django 5.1.4 on 2025-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_ctaima_app', '0017_documenttype_pattern_invalidation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtovalidate',
            name='expected_value',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
