MOCK_DOCUMENT_URLS = [
    'https://drive.google.com/file/d/1xGf3MYatgrICe-1PDJOYrcBzEWPvRm9j/view',
    'https://drive.google.com/file/d/1rN4l334TxfDn1h3z38t6tloSSSEvWPsH/view',
    'https://drive.google.com/file/d/1YCNgvfr9og7CPP6mHIkGMjyP9cAyKZJ8/view',
    'https://drive.google.com/file/d/1W9P42wpga-QcPwEJa7hEL9ZD8K8V3jSl/view',
    'https://drive.google.com/file/d/1maYCuIDXMTRi9V7OMNVr3htEKZeX1tKh/view',
    'https://drive.google.com/file/d/1DpRIoSeMu04BijYnAuJtRRVGy6XrfeHm/view',
    'https://drive.google.com/file/d/1SH5ylwKrz3tyMkMMj1qeCMyvaGkbOBko/view',
    'https://drive.google.com/file/d/1XC_vT_PDTLW7CgPIZmd4ERDAHUUdX48j/view',
    'https://drive.google.com/file/d/1Op27hOE0k_VadPDPZvLsJBFXWr1JE01p/view',
    'https://drive.google.com/file/d/1or8_JIvOwUTTSfJKS7RIgrMLtWUtNpkT/view',
    'https://drive.google.com/file/d/13m_v3g6V9tzZCzbTsVowR2VrumPCMqzO/view',
    'https://drive.google.com/file/d/1dEjx5v0vtmjSZvxtSeQLjA0KKnMNthfL/view',
    'https://drive.google.com/file/d/1P582XjfcV1PrOVWt5ioXp8xz7YN7xope/view',
    'https://drive.google.com/file/d/1mD7Tmho2pFNE8rtI-JBWRulvNo7thfDJ/view',
    'https://drive.google.com/file/d/1TxbZnZRuuoG_PK53_fp3ZCOkclMdSwsQ/view',
] 